name: Release Images

on:
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e
            
            cd ${{ github.repository }}
            git fetch --all
            git checkout ${{ inputs.release_tag }}

            RELEASE_TAG=${{ inputs.release_tag }} docker compose -f docker-compose.yml pull
            RELEASE_TAG=${{ inputs.release_tag }} docker compose -f docker-compose.yml up -d
