name: "changelog"

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.web
    restart: always
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      - NODE_ENV=production
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.api
    restart: always
    command: bun run dist/src/index.js
    expose:
      - 4000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - RESEND_API_KEY=1000000000000000000000000000
    depends_on:
      - migrator
  migrator:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.api
    command: bun run dist/scripts/migrate.js
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - web
volumes:
  pgdata:
