name: "rolled-out"

services:
  web:
    image: ghcr.io/spicysauce-xyz/rolled-out-web:${RELEASE_TAG:-latest}
    restart: always
    expose:
      - 3000
    environment:
      - API_HOST=${DOMAIN}
      - API_PATH=${API_PATH:-/api}
  api:
    image: ghcr.io/spicysauce-xyz/rolled-out-api:${RELEASE_TAG:-latest}
    restart: always
    command: bun run dist/src/index.js
    expose:
      - 4000
    environment:
      - CLIENT_HOST=${DOMAIN}
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - RESEND_API_KEY=1000000000000000000000000000
    depends_on:
      - migrator
  migrator:
    image: ghcr.io/spicysauce-xyz/rolled-out-api:${RELEASE_TAG:-latest}
    command: bun run dist/scripts/migrate.js
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:stable-alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
      - /etc/ssl/cloudflare:/etc/ssl/cloudflare:ro
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - api
      - web
    entrypoint: ["/entrypoint.sh"]
volumes:
  pgdata:
