name: "rolled-out-local"

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.web
    command: bun run server.prod.ts
    restart: always
    expose:
      - 3000
    environment:
      - SELF=http://localhost/admin
      - API=http://localhost/interface
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.api
    restart: always
    command: bun run dist/src/index.js
    expose:
      - 4000
    environment:
      - SELF=http://localhost/interface
      - CLIENT=http://localhost/admin
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - RESEND_API_KEY=1000000000000000000000000000
    depends_on:
      - migrator
  migrator:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.api
    command: bun run dist/scripts/migrate.js
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf.template:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
    environment:
      - API=/interface
      - CLIENT=/admin
    depends_on:
      - api
      - web
    entrypoint: ["/entrypoint.sh"]
volumes:
  pgdata:
