name: "rolled-out"

services:
  traefik:
    image: traefik:v3.0
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/ssl/cloudflare:/certs:ro
      - ./traefik.yml:/etc/traefik.yml:ro
    command:   
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.file.filename=/etc/traefik.yml
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
    restart: always

  web:
    image: ghcr.io/spicysauce-xyz/rolled-out-web:${RELEASE_TAG:-latest}
    restart: always
    expose:
      - 3000
    environment:
      - SELF=https://app.${DOMAIN}
      - API=https://api.${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`app.${DOMAIN}`)
      - traefik.http.routers.web.entrypoints=websecure
      - traefik.http.routers.web.tls=true
      - traefik.http.services.web.loadbalancer.server.port=3000
  
  api:
    image: ghcr.io/spicysauce-xyz/rolled-out-api:${RELEASE_TAG:-latest}
    restart: always
    command: node dist/index.js
    expose:
      - 4000
    environment:
      - SELF=https://api.${DOMAIN}
      - CLIENT=https://app.${DOMAIN}
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_DOMAIN=${RESEND_DOMAIN}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ASSETS_BASE=${S3_ASSETS_BASE}
    depends_on:
      - migrator
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls=true
      - traefik.http.services.api.loadbalancer.server.port=4000
  
  migrator:
    image: ghcr.io/spicysauce-xyz/rolled-out-api:${RELEASE_TAG:-latest}
    command: node dist/scripts/migrate.js
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata:
