name: "rolled-out-local"

services:
  migrator:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.api
    command: node dist/scripts/migrate.js
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
