packages:
  - apps/*
  - packages/*

catalog:
  typescript: 5.8.2
  hono: 4.9.6
  react: 19.1.0
  react-dom: 19.1.0
  vite: 6.3.5
  "@types/react": 19.1.0
  "@types/react-dom": 19.1.0
  "better-auth": "^1.3.4"
