name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build.yml
    with:
      release_tag: ${{ github.event.release.tag_name }}

  release:
    needs: build
    uses: ./.github/workflows/release.yml
    secrets:
      DEPLOYMENT_API_KEY: ${{ secrets.DEPLOYMENT_API_KEY }}
      DEPLOYMENT_URL: ${{ secrets.DEPLOYMENT_URL }}
      DEPLOYMENT_DATABASE_ID: ${{ secrets.DEPLOYMENT_DATABASE_ID }}
      DEPLOYMENT_API_ID: ${{ secrets.DEPLOYMENT_API_ID }}
      DEPLOYMENT_WEB_ID: ${{ secrets.DEPLOYMENT_WEB_ID }}
      DEPLOYMENT_HOCUS_ID: ${{ secrets.DEPLOYMENT_HOCUS_ID }}
      DEPLOYMENT_PUBLIC_ID: ${{ secrets.DEPLOYMENT_PUBLIC_ID }}
      DEPLOYMENT_MARKETING_ID: ${{ secrets.DEPLOYMENT_MARKETING_ID }}
