name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build.yml
    with:
      release_tag: ${{ github.event.release.tag_name }}

  release:
    needs: build
    uses: ./.github/workflows/release.yml
    with:
      release_tag: ${{ github.event.release.tag_name }}
      domain: ${{ vars.DOMAIN }}
      resend_domain: ${{ vars.RESEND_DOMAIN }}
    secrets:
      DO_HOST: ${{ secrets.DO_HOST }}
      DO_USER: ${{ secrets.DO_USER }}
      DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_ASSETS_BASE: ${{ secrets.S3_ASSETS_BASE }}

