name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/steps/build.yml
    with:
      release_tag: ${{ github.event.release.tag_name }}

  deploy:
    needs: build
    uses: ./.github/workflows/steps/release.yml
    with:
      release_tag: ${{ github.event.release.tag_name }}
