name: Build and Push Images

on:
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image_suffix: web
            dockerfile: ./apps/web/Dockerfile.web
            build_args: |
              BUILDKIT_PROGRESS=plain
              VERSION=${{ inputs.release_tag }}

          - image_suffix: api
            dockerfile: ./apps/api/Dockerfile.api
            build_args: |
              BUILDKIT_PROGRESS=plain

          - image_suffix: db
            dockerfile: ./packages/db/Dockerfile.db
            build_args: |
              BUILDKIT_PROGRESS=plain

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.image_suffix }} image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-${{ matrix.image_suffix }}:${{ inputs.release_tag }}
            ghcr.io/${{ github.repository }}-${{ matrix.image_suffix }}:latest
          build-args: ${{ matrix.build_args }}
