name: Build and Push Images

on:
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/web/Dockerfile.web
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-web:${{ inputs.release_tag }}
            ghcr.io/${{ github.repository }}-web:latest
          build-args: |
            BUILDKIT_PROGRESS=plain

      - name: Build and push api image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile.api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-api:${{ inputs.release_tag }}
            ghcr.io/${{ github.repository }}-api:latest
          build-args: |
            BUILDKIT_PROGRESS=plain
