name: Release Images

on:
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string
      domain:
        required: true
        type: string
      resend_domain:
        required: true
        type: string
    secrets:
      RESEND_API_KEY:
        required: true
      DO_HOST:
        required: true
      DO_USER:
        required: true
      DO_SSH_KEY:
        required: true
      S3_ENDPOINT:
        required: true
      S3_ACCESS_KEY_ID:
        required: true
      S3_SECRET_ACCESS_KEY:
        required: true
      S3_BUCKET_NAME:
        required: true
      S3_ASSETS_BASE:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e
            
            cd ${{ github.repository }}
            git fetch --all
            git checkout ${{ inputs.release_tag }}

            export RELEASE_TAG="${{ inputs.release_tag }}"
            export DOMAIN="${{ inputs.domain }}"
            export RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}"
            export RESEND_DOMAIN="${{ inputs.resend_domain }}"
            export S3_ENDPOINT="${{ secrets.S3_ENDPOINT }}"
            export S3_ACCESS_KEY_ID="${{ secrets.S3_ACCESS_KEY_ID }}"
            export S3_SECRET_ACCESS_KEY="${{ secrets.S3_SECRET_ACCESS_KEY }}"
            export S3_BUCKET_NAME="${{ secrets.S3_BUCKET_NAME }}"
            export S3_ASSETS_BASE="${{ secrets.S3_ASSETS_BASE }}"

            docker compose -f docker-compose.production.yml pull
            docker compose -f docker-compose.production.yml up -d
