name: Release Images

on:
  workflow_run:
    workflows: ["Build and Push Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e

            echo "🔄 Pulling latest code"
            
            cd ${{ secrets.DO_USER }}/${{ github.repository }}
            git fetch --all
            git checkout ${{ github.event.release.tag_name }}
            git reset --hard origin/${{ github.event.release.tag_name }}

            echo "🚀 Starting Docker Compose with tag ${{ github.event.release.tag_name }}"

            RELEASE_TAG=${{ github.event.release.tag_name }} docker compose -f docker-compose.yml pull
            RELEASE_TAG=${{ github.event.release.tag_name }} docker compose -f docker-compose.yml up -d

            echo "✅ Deployment complete!"
