name: Release Application

on:
  workflow_call:
    secrets:
      DEPLOYMENT_API_KEY:
        required: true
      DEPLOYMENT_URL:
        required: true
      DEPLOYMENT_DATABASE_ID:
        required: true
      DEPLOYMENT_API_ID:
        required: true
      DEPLOYMENT_WEB_ID:
        required: true
      DEPLOYMENT_HOCUS_ID:
        required: true
      DEPLOYMENT_PUBLIC_ID:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Database
        uses: benbristow/dokploy-deploy-action@0.0.1
        with:
          auth_token: ${{ secrets.DEPLOYMENT_API_KEY }}
          application_id: ${{ secrets.DEPLOYMENT_DATABASE_ID }}
          dokploy_url: ${{ secrets.DEPLOYMENT_URL }}

      - name: Deploy API
        uses: benbristow/dokploy-deploy-action@0.0.1
        with:
          auth_token: ${{ secrets.DEPLOYMENT_API_KEY }}
          application_id: ${{ secrets.DEPLOYMENT_API_ID }}
          dokploy_url: ${{ secrets.DEPLOYMENT_URL }}

      - name: Deploy Web
        uses: benbristow/dokploy-deploy-action@0.0.1
        with:
          auth_token: ${{ secrets.DEPLOYMENT_API_KEY }}
          application_id: ${{ secrets.DEPLOYMENT_WEB_ID }}
          dokploy_url: ${{ secrets.DEPLOYMENT_URL }}

      - name: Deploy Hocus
        uses: benbristow/dokploy-deploy-action@0.0.1
        with:
          auth_token: ${{ secrets.DEPLOYMENT_API_KEY }}
          application_id: ${{ secrets.DEPLOYMENT_HOCUS_ID }}
          dokploy_url: ${{ secrets.DEPLOYMENT_URL }}

      - name: Deploy Public
        uses: benbristow/dokploy-deploy-action@0.0.1
        with:
          auth_token: ${{ secrets.DEPLOYMENT_API_KEY }}
          application_id: ${{ secrets.DEPLOYMENT_PUBLIC_ID }}
          dokploy_url: ${{ secrets.DEPLOYMENT_URL }}
