name: Release Application

on:
  workflow_call:
    secrets:
      DEPLOYMENT_API_KEY:
        required: true
      DEPLOYMENT_URL:
        required: true
      DEPLOYMENT_DATABASE_ID:
        required: true
      DEPLOYMENT_API_ID:
        required: true
      DEPLOYMENT_WEB_ID:
        required: true
      DEPLOYMENT_HOCUS_ID:
        required: true
      DEPLOYMENT_PUBLIC_ID:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Database
        uses: dokploy/dokploy-action@v1
        run: |
            curl -X 'POST' \
            '${{ secrets.DEPLOYMENT_URL }}/api/trpc/application.deploy' \
            -H 'accept: application/json' \
            -H 'x-api-key: ${{ secrets.DEPLOYMENT_API_KEY }}' \
            -H 'Content-Type: application/json' \
            -d '{
                "json":{
                    "applicationId": "${{ secrets.DEPLOYMENT_DATABASE_ID }}"
                }
            }'

      - name: Deploy API
        uses: dokploy/dokploy-action@v1
        run: |
            curl -X 'POST' \
            '${{ secrets.DEPLOYMENT_URL }}/api/trpc/application.deploy' \
            -H 'accept: application/json' \
            -H 'x-api-key: ${{ secrets.DEPLOYMENT_API_KEY }}' \
            -H 'Content-Type: application/json' \
            -d '{
                "json":{
                    "applicationId": "${{ secrets.DEPLOYMENT_API_ID }}"
                }
            }'

      - name: Deploy Web
        uses: dokploy/dokploy-action@v1
        run: |
            curl -X 'POST' \
            '${{ secrets.DEPLOYMENT_URL }}/api/trpc/application.deploy' \
            -H 'accept: application/json' \
            -H 'x-api-key: ${{ secrets.DEPLOYMENT_API_KEY }}' \
            -H 'Content-Type: application/json' \
            -d '{
                "json":{
                    "applicationId": "${{ secrets.DEPLOYMENT_WEB_ID }}"
                }
            }'

      - name: Deploy Hocus
        uses: dokploy/dokploy-action@v1
        run: |
            curl -X 'POST' \
            '${{ secrets.DEPLOYMENT_URL }}/api/trpc/application.deploy' \
            -H 'accept: application/json' \
            -H 'x-api-key: ${{ secrets.DEPLOYMENT_API_KEY }}' \
            -H 'Content-Type: application/json' \
            -d '{
                "json":{
                    "applicationId": "${{ secrets.DEPLOYMENT_HOCUS_ID }}"
                }
            }'

      - name: Deploy Public
        uses: dokploy/dokploy-action@v1
        run: |
            curl -X 'POST' \
            '${{ secrets.DEPLOYMENT_URL }}/api/trpc/application.deploy' \
            -H 'accept: application/json' \
            -H 'x-api-key: ${{ secrets.DEPLOYMENT_API_KEY }}' \
            -H 'Content-Type: application/json' \
            -d '{
                "json":{
                    "applicationId": "${{ secrets.DEPLOYMENT_PUBLIC_ID }}"
                }
            }'
